INSERT INTO user (user_id, username, password) VALUES (NEXT VALUE FOR seq_user, 'test', '$2a$10$noy/uCM5szmi0f4E8r.i6.d5Fymjc2Ob8.55nvV/klt7twf6Lxk1y');
INSERT INTO category (category_id, name, user_id) VALUES (NEXT VALUE FOR seq_category, 'Riided', 1);
INSERT INTO category (category_id, name, user_id) VALUES (NEXT VALUE FOR seq_category, 'Toidukaubad', 1);
INSERT INTO category (category_id, name, user_id) VALUES (NEXT VALUE FOR seq_category, 'Meelelahutus', 1);
INSERT INTO category (category_id, name, user_id) VALUES (NEXT VALUE FOR seq_category, 'Kodutarbed', 1);
INSERT INTO category (category_id, name, user_id) VALUES (NEXT VALUE FOR seq_category, 'Elektroonika', 1);
INSERT INTO expense(expense_id, category_id, user_id, insertion_time, comment, amount) VALUES (NEXT VALUE FOR seq_expense, 1, 1, '2017-08-16 09:37:38','useful', 24.50);
INSERT INTO expense(expense_id, category_id, user_id, insertion_time, comment, amount) VALUES (NEXT VALUE FOR seq_expense, 2, 1, '2017-08-16 09:37:38','toit1', 5);
INSERT INTO expense(expense_id, category_id, user_id, insertion_time, comment, amount) VALUES (NEXT VALUE FOR seq_expense, 2, 1, '2017-08-16 09:37:38','toit2', 10);
INSERT INTO expense(expense_id, category_id, user_id, insertion_time, comment, amount) VALUES (NEXT VALUE FOR seq_expense, 5, 1, '2017-08-16 09:37:38','mp3', 2000);
INSERT INTO expense(expense_id, category_id, user_id, insertion_time, comment, amount) VALUES (NEXT VALUE FOR seq_expense, 5, 1, '2019-04-16 09:37:38','ipad', 400);
INSERT INTO expense(expense_id, category_id, user_id, insertion_time, comment, amount) VALUES (NEXT VALUE FOR seq_expense, 5, 1, '2019-04-01 09:37:38','autopesu', 40);
